apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: jw-workshop-deployment
  labels:
    app: jw-workshop-node
spec:
  selector:
    matchLabels:
      app: jw-workshop
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: jw-workshop
    spec:
      containers:
              - image: dillson/jw-workshop:latest
        name: jw-workshop-node
        ports:
        - containerPort: 8080
          name: jw-workshop-node
